<?php

/**
 * Implements hook_views_data_alter().
 */
function domain_access_search_api_views_data_alter(array &$data) {

  $table = 'search_api_datasource_resources_index_entity_node';
  // Current domain filter.
  $data[$table]['current_all'] = [
    'title' => t('Search API: Current domain'),
    'group' => t('Domain'),
    'filter' => [
      'field' => 'field_domain_access',
      'id' => 'domain_access_search_api_current_all_filter',
      'title' => t('Search API: Available on current domain'),
      'help' => t('Filters out nodes available on current domain (published to current domain or all affiliates).'),
    ],
  ];
  // Since domains are not stored in the database, relationships cannot be used.
  unset($data[$table][DOMAIN_ACCESS_FIELD]['relationship']);
}
