<?php

use Drupal\search_api\Entity\Index;

/**
 * Implements hook_views_data_alter().
 */
function domain_access_search_api_views_data_alter(array &$data) {

  /** @var \Drupal\search_api\IndexInterface $index */
  foreach (Index::loadMultiple() as $index) {
    try {
      $table = 'search_api_index_' . $index->id();
      // Current domain filter.
      $data[$table]['current_all'] = [
        'title' => t('Search API: Current domain'),
        'group' => t('Domain'),
        'filter' => [
          'field' => 'field_domain_access',
          'id' => 'domain_access_search_api_current_all_filter',
          'title' => t('Search API (' . $index->id() . '): Available on current domain'),
          'help' => t('Filters out nodes available on current domain (published to current domain or all affiliates).'),
        ],
      ];
      // Since domains are not stored in the database, relationships cannot be used.
      unset($data[$table][DOMAIN_ACCESS_FIELD]['relationship']);
    }
    catch (\Exception $e) {
      $args = [
        '%index' => $index->label(),
      ];
      watchdog_exception('search_api', $e, '%type while computing Views data for index %index: @message in %function (line %line of %file).', $args);
    }
  }
}
